source ~/.vimrc/general.vim
source ~/.vimrc/gui.vim
source ~/.vimrc/filetype.vim
source ~/.vimrc/plugins.vim
source ~/.vimrc/align.vim
source ~/.vimrc/completion.vim
source ~/.vimrc/fuzzy.vim
source ~/.vimrc/markdown.vim
source ~/.vimrc/nerdtree.vim
source ~/.vimrc/sneak.vim
source ~/.vimrc/whitespace.vim
